spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interface_db
    username: postgres
    password: example
    platform: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    jcache:
      config: ehcache.xml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: collector
server:
  port: 5679
jwt:
  sessionTime: 120000000
  secret: asdf123123

