spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/machine
    username: postgres
    password: 123030
    platform: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    jcache:
      config: ehcache.xml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: collector
server:
  port: 5678


